name: deploy-lambda
description: Deploys the selected environment
branding: {color: blue, icon: box}
inputs:
  environment: {description: environment name, required: true}
  AWS_ACCESS_KEY_ID_DEV: {description: dev aws access key id, required: true}
  AWS_SECRET_ACCESS_KEY_DEV: {description: dev aws secret access key, required: true}
  AWS_ACCESS_KEY_ID_TEST: {description: test aws access key id, required: true}
  AWS_SECRET_ACCESS_KEY_TEST: {description: test aws secret access key, required: true}
  AWS_ACCESS_KEY_ID_PROD: {description: prod aws access key id, required: true}
  AWS_SECRET_ACCESS_KEY_PROD: {description: prod aws secret access key, required: true}
  AWS_ACCESS_KEY_ID_CHINA: {description: china aws access key id, required: true}
  AWS_SECRET_ACCESS_KEY_CHINA: {description: china aws secret access key, required: true}
runs:
  on: ubuntu-latest
  strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
      run: |
        node --version
        npm --version
        npm ci
        yarn test
        mkdir -p ~/.aws
        cat << EOF > ~/.aws/credentials
        [devProfile]
        region=eu-west-1
        aws_access_key_id=${{inputs.AWS_ACCESS_KEY_ID_DEV}}
        aws_secret_access_key=${{inputs.AWS_SECRET_ACCESS_KEY_DEV}}
        [testProfile]
        region=eu-west-1
        aws_access_key_id=${{inputs.AWS_ACCESS_KEY_ID_TEST}}
        aws_secret_access_key=${{inputs.AWS_SECRET_ACCESS_KEY_TEST}}
        [prodProfile]
        region=eu-west-1
        aws_access_key_id=${{inputs.AWS_ACCESS_KEY_ID_PROD}}
        aws_secret_access_key=${{inputs.AWS_SECRET_ACCESS_KEY_PROD}}
        [chinaProfile]
        region=cn-north-1
        aws_access_key_id=${{inputs.AWS_ACCESS_KEY_ID_CHINA}}
        aws_secret_access_key=${{inputs.AWS_SECRET_ACCESS_KEY_CHINA}}
        EOF
        yarn sls deploy -s ${{inputs.environment}} --aws-s3-accelerate
        rm ~/.aws/credentials
