name: deploy-lambda
description: Deploys the selected environment
branding: { color: blue, icon: box }
inputs:
  environment: { description: environment name, required: true }
  node-version: {
    description: Node version to test the lambda,
    required: false,
    default: '16'
  }
  AWS_ACCESS_KEY_ID_DEV: { description: dev aws access key id, required: true }
  AWS_SECRET_ACCESS_KEY_DEV: { description: dev aws secret access key, required: true }
  AWS_ACCESS_KEY_ID_TEST: { description: test aws access key id, required: true }
  AWS_SECRET_ACCESS_KEY_TEST: { description: test aws secret access key, required: true }
  AWS_ACCESS_KEY_ID_PROD: { description: prod aws access key id, required: true }
  AWS_SECRET_ACCESS_KEY_PROD: { description: prod aws secret access key, required: true }
  AWS_ACCESS_KEY_ID_CHINA: { description: china aws access key id, required: true }
  AWS_SECRET_ACCESS_KEY_CHINA: { description: china aws secret access key, required: true }
  ABI_DATABASE_GATEWAY_DEPLOY_KEY: { description: Private database gateway repository deploy key, required: true }
  LIBBY_DEPLOY_KEY: { description: Private libby repository deploy key, required: true }
runs:
  using: composite
  steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: "Get deploy keys for Abi dependencies"
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
          ${{ inputs.ABI_DATABASE_GATEWAY_DEPLOY_KEY }}
          ${{ inputs.LIBBY_DEPLOY_KEY }}

    - name: ⚙️ Configure Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        registry-url: https://npm.pkg.github.com

    - name: 📺 Run tests
      shell: bash
      run: |
        node --version
        npm --version
        npm ci
        yarn test

    - name: 📡 Deploy the lambda function
      shell: bash
      run: |
        mkdir -p ~/.aws
        cat << EOF > ~/.aws/credentials
        [devProfile]
        region=eu-west-1
        aws_access_key_id=${{inputs.AWS_ACCESS_KEY_ID_DEV}}
        aws_secret_access_key=${{inputs.AWS_SECRET_ACCESS_KEY_DEV}}
        [testProfile]
        region=eu-west-1
        aws_access_key_id=${{inputs.AWS_ACCESS_KEY_ID_TEST}}
        aws_secret_access_key=${{inputs.AWS_SECRET_ACCESS_KEY_TEST}}
        [prodProfile]
        region=eu-west-1
        aws_access_key_id=${{inputs.AWS_ACCESS_KEY_ID_PROD}}
        aws_secret_access_key=${{inputs.AWS_SECRET_ACCESS_KEY_PROD}}
        [chinaProfile]
        region=cn-north-1
        aws_access_key_id=${{inputs.AWS_ACCESS_KEY_ID_CHINA}}
        aws_secret_access_key=${{inputs.AWS_SECRET_ACCESS_KEY_CHINA}}
        EOF
        yarn sls deploy -s ${{inputs.environment}} --aws-s3-accelerate
        rm ~/.aws/credentials
